version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "
        sleep 2 &&
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/code
    environment:
      - DB_HOST=db
      - DB_PORT=5433
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=password

  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5433"
    command: -p 5433
    volumes:
      - postgres_data:/var/lib/postgresql@14/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: