version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "
        sleep 2 &&
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/code

  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5433"
    command: -p 5433
    volumes:
      - postgres_data:/var/lib/postgresql@14/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 3s
      retries: 3

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A proposalapp worker --loglevel=info
    depends_on:
      - web
      - rabbitmq
    volumes:
      - .:/code


volumes:
  postgres_data: