# Generated by Django 4.2.2 on 2023-06-16 12:28

import cpf_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('cpf', cpf_field.models.CPFField(max_length=14, verbose_name='cpf')),
                ('address', models.CharField(max_length=255, verbose_name='Endereço')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Empréstimo Pretendido')),
                ('status', models.CharField(default='pending', max_length=255)),
            ],
        ),
    ]
