# Generated by Django 4.2.2 on 2023-06-16 14:10

import cpf_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='cpf',
            field=cpf_field.models.CPFField(max_length=14, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('approved', 'Aprovado'), ('refused', 'Recusado'), ('pending', 'Pendente')], default='pending', max_length=255),
        ),
    ]
